### PR TITLE
Add a blurb for the ARM64 track, fixes #28

### LINKED ISSUE #28: Add language blurb
The track's `config.json` file must have a non-empty `blurb` property. This property should contain a short description (less than or equal to 400 characters) of the language. See https://github.com/exercism/docs/blob/main/building/tracks/config-json.md.

## Tracking

https://github.com/exercism/v3-launch/issues/37

### PR DESCRIPTION
**Pull request by Chlorophytus**
[The ARM64 track needs a blurb.](https://github.com/exercism/arm64-assembly/issues/28)

### CODE REVIEW

**Review by BethanyG — APPROVED** [review]
LGTM!  🌟

**Comment by BethanyG** [comment]
However, the CI is failing due to required config entries and missing directories and files.  In order to merge this, those missing items will need to be addressed for the track.

**Review by ErikSchierboom — APPROVED** [review]

**Comment by ErikSchierboom** [comment]
@BethanyG Not required for me :P

**Comment by ErikSchierboom** [comment]
Thanks @Chlorophytus!

**Comment by Chlorophytus** [comment]
> However, the CI is failing due to required config entries and missing directories and files. In order to merge this, those missing items will need to be addressed for the track

@BethanyG @ErikSchierboom It's my first time contributing to a language track, I am curious what the other requirements are for this to be a track that *could* be enabled later on if there's a demand.

---
I've heard of a slack that track maintainers use. We may be able to discuss plans for enabling the track there. :)

**Comment by ErikSchierboom** [comment]
Could you email me at erik @ exercism.io? I'll send you some pointers and link you to the slack workspace.

**Pull request merged**
